### ISSUE TITLE
API for moderator 

### ISSUE THREAD

**Issue by vovanb** [nvonahsen/jitsi-token-moderation-plugin#1]
I have list of questions that can't found answers:

if exist API for create room and get uniquely link?

if exist API to mute voice for all participants in room? and user can not enable it

if exist API to mute camera for all participants in room? and user can not enable it

if exist API to disconnect specific participants in room?

if exist exist API to create password for each participants before joining room

if exist a way to create branding for application without build custom native apps?

how to disable option that users can kick-off another user?

**Comment by lggwettmann** [comment]
If I understand correctly, I think most of your questions are unrelated to this plugin. This plugin only makes sure that users get moderator status if ```moderator: true``` in the JWT token. Nothing else. If you want to enable other features, you'll have to use other integrations, plugins, or find a way yourself, I'm afraid.

**Comment by bryanasdev000** [comment]
Hi @vovanb!

What @lggwettmann said pretty much sums up the question.

However, it is good to answer some of your questions directly for documentation purposes.

For the unique link, input a random string after you jitsi domain, something like that https://meet.mydomain/WonderfulPupilsPursueJealously , this is the way it already works.

For the kick and mute features this is exposed by the jitsi-meet (if i remember correctly) to all **moderators** in the room, if you want this exposed to another application you may need to read the jitsi-meet code.

To create a "password" for each room im not sure if its supported, need to read the docs, but basicaly you can use JWT to do that.

About branding depends what you want, if you need a custom UI you will need to code it (see Jitsi team repo, there are a few useful things about that there), but if you want to just change the logo and embedd in another page is relativily easy to do so.
