### ISSUE TITLE
Jibri Does Not Work

### ISSUE THREAD

**Issue by xceejay** [nvonahsen/jitsi-token-moderation-plugin#3]
Hello good tool, but once i enable this, recording fails to work, the record button does not even show, but once i disable it jibri starts to work again

**Comment by bryanasdev000** [comment]
Hi @xceejay !

This is a "limitation" of the Jibri and has no specific relationship with this plugin, as this happens with other means of authentication. You can take a look here https://community.jitsi.org/t/jibri-authenticating-if-a-room-has-a-password-added-by-moderator/18775/25 to understand and try a possible solution.

**Comment by bryanasdev000** [comment]
Hi @xceejay !

Could you try again after pull request #10?

Thank you!

**Comment by xceejay** [comment]
Thank you!

**Comment by bryanasdev000** [comment]
Since no further activity has appeared on this subject, it will be closed. If you believe it was closed incorrectly or you still have this issue, leave a comment and mention me.
