### ISSUE TITLE
Moodle

### ISSUE THREAD

**Issue by siamitai** [nvonahsen/jitsi-token-moderation-plugin#5]
Goodnight. very good tool. Consulat it is possible to integrate it to moodel when a teacher agrees to be moderated and when a student accesses it is not a moderator. Thanks a lot

**Comment by bryanasdev000** [comment]
Hi @siamitai !

There is a moodle plugin available which use this plugin do exactly that.

Link: https://github.com/udima-university/moodle-mod_jitsi
