### ISSUE TITLE
Unable to see anything working

### ISSUE THREAD

**Issue by eNirantar** [nvonahsen/jitsi-token-moderation-plugin#9]
I have tried the same , i did not able to see any logs , it is not working not even error i am getting.

**Comment by eNirantar** [comment]
> I have tried the same , i did not able to see any logs , it is not working not even error i am getting.

![image](https://user-images.githubusercontent.com/43892300/83396931-6511ed00-a41a-11ea-9965-276462dde112.png)



what if we do not pass jwt. it does not create moderator but it should log something in console correct

**Comment by bryanasdev000** [comment]
Hi @eNirantar !

The code itself doesnt log if you dont have a JWT token, the responsible for that is https://github.com/jitsi/jitsi-meet/blob/master/resources/prosody-plugins/mod_token_verification.lua which handles the JWT. This plugin only handle the moderator field of the JWT to do its magic.
